name: Run Dhaka Dispatch Automation

on:
  # Schedule to run every day at 6:00 PM UTC
  schedule:
    - cron: '0 15 * * *'
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        # Use npm ci for fast, reliable installs in CI
        run: npm ci

      - name: Run Puppeteer Automation Script
        run: node e2e-script.js
        env:
          APP_URL: ${{ secrets.APP_URL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
